[package]
name = "owoify"
version = "0.1.0"
authors = ["MrEvilCookie <evilcookiemail@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.2.0"
rand = "0.7.0"
